# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: 'authors/admin'
    weight: 10
  - name: Working papers
    url: '#working-papers'
    weight: 20
  - name: Work in progress
    url: '#work-in-progress'
    weight: 30
  - name: Teaching
    url: 'teaching'
    weight: 40
  - name: Resources
    url: 'resources'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  - name: CV
    url: uploads/GMCesar_CV.pdf
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
